# Generated by Django 4.0.4 on 2022-04-27 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertiser',
            name='email',
            field=models.EmailField(max_length=255, verbose_name='email address'),
        ),
    ]
