# Generated by Django 4.0.4 on 2022-04-27 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisers', '0002_alter_advertiser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertiser',
            name='address',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='advertiser',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='advertiser',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=255, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='advertiser',
            name='name',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
    ]
