# Generated by Django 4.0.4 on 2022-04-27 07:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=65, unique=True)),
                ('advertiser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('naver', 'Naver'), ('kakao', 'Kakao'), ('google', 'Google'), ('facebook', 'Facebook')], max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='AdvertisementsInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.PositiveIntegerField()),
                ('impression', models.PositiveIntegerField()),
                ('click', models.PositiveIntegerField()),
                ('conversion', models.PositiveIntegerField()),
                ('cv', models.PositiveIntegerField()),
                ('created_at', models.DateField()),
                ('updated_at', models.DateField()),
                ('advertisement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advertisements.advertisements')),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advertisements.media')),
            ],
        ),
    ]
