# Generated by Django 4.0.4 on 2022-04-28 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisementinfo',
            name='date',
            field=models.DateField(blank=True, default=''),
        ),
    ]
