# Generated by Django 4.0.4 on 2022-04-29 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='advertisementinfo',
            index=models.Index(fields=['advertisement'], name='advertisement_uid_idx'),
        ),
        migrations.AddIndex(
            model_name='advertisementinfo',
            index=models.Index(fields=['date'], name='advertisement_info_idx'),
        ),
    ]
